### ISSUE TITLE
use goodpractice dev version instead of released version?

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/roreviewapi#16]
cf https://github.com/ropensci/dev_guide/issues/325#issue-854460764

**Comment by mpadge** [comment]
@maelle Note that i have not checked whether the current dev version works as expected!! Shall have to do that prior to re-deploying the container.

**Comment by mpadge** [comment]
I had a play with it just now, and it caused an internal segfault through `covr` on one package, but otherwise seemed stable. `covr` is more regularly maintained than `goodpractice` itself, so I'll optimistically leave the dev version in the container until we potentially discover otherwise.
