### ISSUE TITLE
Coverage report for gittargets submission

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/roreviewapi#20]
https://github.com/ropensci/software-review/issues/486 gives only 13%, but according to @wlandau should be much higher, and so something has gone wrong. Check and fix.

**Comment by mpadge** [comment]
@wlandau `tar_git_okay()` is `TRUE`, but coverage looks like this:

```
gittargets Coverage: 13.82%
R/tar_git_checkout.R: 0.00%
R/tar_git_init.R: 0.00%
R/tar_git_log.R: 0.00%
R/tar_git_ok.R: 0.00%
R/tar_git_snapshot.R: 0.00%
R/tar_git_status_code.R: 0.00%
R/tar_git_status_data.R: 0.00%
R/tar_git_status_targets.R: 0.00%
R/tar_git_status.R: 0.00%
R/utils_assert.R: 0.00%
R/utils_git.R: 33.33%
R/utils_cli.R: 81.25%
R/utils_data.R: 93.33%
R/utils_logic.R: 100.00%
```

It's definitely something fundamental with `tar_git`, but I've no idea where to look next, so any further insights from your side would be appreciated, thanks :smile:

**Comment by wlandau-lilly** [comment]
Thanks for looking into this. Coverage at https://github.com/wlandau/gittargets/runs/4243387237?check_suite_focus=true#step:9:36 is 100%, and when I remove Git configuration locally so that `gittargets::tar_git_ok()` is `FALSE`, coverage is actually higher than the 13.3% (using https://github.com/wlandau/gittargets/commit/e5d710e046b80a4ec14bf6672d89bf653c68c27c).

```r
gittargets Coverage: 29.04%
R/tar_git_checkout.R: 0.00%
R/tar_git_init.R: 0.00%
R/tar_git_log.R: 0.00%
R/tar_git_snapshot.R: 0.00%
R/tar_git_status_code.R: 0.00%
R/tar_git_status_data.R: 0.00%
R/tar_git_status_targets.R: 0.00%
R/tar_git_status.R: 0.00%
R/utils_assert.R: 0.00%
R/utils_git.R: 48.72%
R/utils_cli.R: 81.25%
R/utils_data.R: 93.33%
R/tar_git_ok.R: 100.00%
R/utils_logic.R: 100.00%
```

To answer your questions,

1. Those AWS keys are tech debt from another project and are not used in `gittargets`. I removed them in the latest commit.
2. I will try the Ubuntu runner for coverage.

**Comment by wlandau** [comment]
Update: the [ubuntu-latest workflow](https://github.com/wlandau/gittargets/blob/main/.github/workflows/cover-ubuntu.yaml) shows [100% coverage](https://github.com/wlandau/gittargets/runs/4243613085?check_suite_focus=true#step:10:39).

What does `covr::zero_coverage()` say for the runner on your end?

**Comment by mpadge** [comment]
@wlandau `testthat:::on_cran()` is `TRUE` in the `covr` environment for your package. That function [just checks for an envvar set by `testthat` called `"NOT_CRAN"`](https://github.com/r-lib/testthat/blob/e27679198811ca7a57bdaefd2747867353c336af/R/skip.R#L131) (which you clearly know, and have in your vignette :smiley:).  `covr` makes a complete local clone of the repo so it can inject modified headers into every function. There must be something in your package that prevents that envvar from being carried over to the `covr` environrment.

You should be able to reproduce by, for example, cloning repo in a clean `tidyverse` docker container, and running `x <- covr::package_coverage()`. I usually diagnose `covr` env issues by setting a file name as an envvar and dumping logs to that, but note that you might face a tricky interaction between `callr` which relies exclusively on `options` and does not  (by default) carry over envvars, and `covr` which effectively does the reverse.

**Comment by wlandau** [comment]
How exactly does `roreviewapi` set `NOT_CRAN`? I have `skip_on_cran()` in several places, and I could remove this for the review as a last resort.

When I run `covr::package_coverage()` in a `rocker/tidyverse` Docker container, I get zero coverage if I do nothing with `NOT_CRAN` and 100% coverage if I run `Sys.setenv(NOT_CRAN = "true")`. To me, this seems to align with expectation.

Locally, I have `NOT_CRAN=true` in `~/.Renviron`, and coverage unsurprisingly drops if I unset it. And on GitHub Actions, it looks like `NOT_CRAN` is set to "true" automatically if the user does not manually set a value (https://github.com/r-lib/actions/blob/e2dce68d708d571055b9dc8f609a461afd95bbea/setup-r/lib/installer.js#L560-L561, https://github.com/r-lib/actions/pull/139/files).

**Comment by mpadge** [comment]
Aha, that all makes sense then! Neither I nor `roreviewapi` use any kind of `NOT_CRAN` variable. Even though the [`testthat` NEWS said when in introduced `skip_on_cran()`](https://github.com/r-lib/testthat/blob/main/NEWS.md) (v0.9) that users would have to set that variable locally, it's been modified since so that all (? most at least) calls are wrapped in `withr::local_envvar(NOT_CRAN = true)`. So `testthat` effectively sets it internally, while `covr` itself uses no such variable. (And i had an illuminating email exchange with Uwe Ligges a few years back after a round of CRAN rejections, at the end of which he strongly advised me not to use or rely on a `NOT_CRAN` variable, and i took him to his word and have kept true to that since.)

Nevertheless, your link above in the `setup-r` installer file would be the reason coverage works on GitHub runners, and strongly suggests we should just mirror that here. Thanks!

**Comment by mpadge** [comment]
Just confirmed 100% coverage with the above commit adding that envvar. Thanks Will!

**Comment by wlandau** [comment]
Thanks for accommodating, @mpadge!
