### ISSUE TITLE
Pre-install Julia

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/roreviewapi#28]
@s3alfisc has now submitted first package which calls external Julia routines. Pre-install via main [`pkgcheck` docker image](https://github.com/ropensci-review-tools/pkgcheck/blob/main/Dockerfile) is easy via apt, but current Ubuntu 20.04 distributes Julia v1.4.1, while actual Julia is 1.7.3.

@s3alfisc Have you got any ideas or opinions as to differences between 1.4 -> 1.7? Hopefully not too much difference, so we can presume that not-exactly-current Ubuntu apt version will always suffice, but I've no idea, and presume you know more about this. Opinions please :+1: Also ping @adamhsparks

**Comment by adamhsparks** [comment]
Yeah, I’m far from an expert, but my first thought was also compatibility issues with the version for the direct Julia code or dependencies as @s3alfisc mentioned.

**Comment by mpadge** [comment]
@s3alfisc The above commit adds latest Julia (currently 1.7.3) to our base container. That itself gets rebuilt at least monthly, so will always be up-to-date. Those changes won't propagate across to our internal system until scheduled rebuild next week (5th July), after which your Julia tests should all work. You should still add control flags througout to avoid fails on systems which don't have Julia, such as all CRAN systems.
