### ISSUE TITLE
Spurious error message

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/roreviewapi#30]
I do not understand this comment https://github.com/ropensci/software-review/issues/418#issuecomment-1188762066 as the submission template does contain this variable

```
<!--due-dates-list-->Due date for @adithirgis: 2021-10-04
Due date for @KevCaz: 2021-10-12<!--end-due-dates-list-->
```

**Comment by maelle** [comment]
New sighting https://github.com/ropensci/software-review/issues/505#issuecomment-1191110290

**Comment by mpadge** [comment]
These were because of our ill-formatted `settings.yaml` file in the bot configuration, which meant that the bot wasn't passing on the proper parameters. Now fixed via https://github.com/ropensci-org/buffy/pull/83
