### ISSUE TITLE
Questions about routes

### ISSUE THREAD

**Issue by sckott** [ropensci-review-tools/roreviewapi#4]
- Why do `/editorcheck`, `/goodtoreview`, and `/stdlogs` routes use POST rather than GET? Seems like all information is passed in the query parameters, which suggests GET is more appropriate. But maybe plumber suggests using POST for some reason?
- Should some of these routes be not open to the public internet? E.g., do you want to require authentication on `/log` so that random folks can't see IP addresses, etc.?

**Comment by mpadge** [comment]
>   Why do `/editorcheck`, `/goodtoreview`, and `/stdlogs` routes use POST rather than GET? Seems like all information is passed in the query parameters, which suggests GET is more appropriate. But maybe plumber suggests using POST for some reason?

You're right - `POST` is a hangover from former incarnations that can and should just be `GET`. I'll change that straight away.
 
>   Should some of these routes be not open to the public internet? E.g., do you want to require authentication on `/log` so that random folks can't see IP addresses, etc.?

Yes indeed! The first point will be addressed straight away, so this issue can remain open for sole purpose of implementing authentication.

**Comment by sckott** [comment]
Cool, I'll test and report back

**Comment by sckott** [comment]
Dockerfile needs a fix, will PR

**Comment by sckott** [comment]
PR opened
