### ISSUE TITLE
Github action to trigger /editorcheck on new issue creation

### ISSUE THREAD

**Issue by sckott** [ropensci-review-tools/roreviewapi#5]
I now have a Github action workflow working for triggering an editor check run on the new server based on a new issue being created. 

Noam said you want editor check to be triggered by bot as needed as well as on new issue creation, so here's the "on new issue creation" piece

I'm using a test repo right now (see links), but should be easy to pop into software review repo - i put ruby files in the .github/workflows folder itself to keep files out of the root repo, but you can put them elsewhere of course. 

The workflow: https://github.com/sckott/studious-computing-machine/blob/main/.github/workflows/check-package.yml

It uses a combination of running on new issue, as well as regex for words in the body of the new issue, right now using `statistical-software-review-book`, BUT you may have something better to use 

Example:
- An issue where a minimal template was used to open an issue and the resulting check results https://github.com/sckott/studious-computing-machine/issues/12
- GH actions run for the same issue https://github.com/sckott/studious-computing-machine/runs/3023854524?check_suite_focus=true

Thoughts? @mpadge  @noamross

**Comment by mpadge** [comment]
That looks great! Only potential issue here is that the bot itself now has the ability to [call an external service in the "Welcome" responder](https://buffy-ropensci.readthedocs.io/en/latest/responders/welcome.html#examples) triggered on issue opening. That means we can only activate one or the other of these workflows, for which my preference would be via `buffy`, simply to avoid increase in locations from which external services are called. What are your thoughts @xuanxu?

**Comment by sckott** [comment]
Sorry, didn't know the bot could be triggered on issue opening. Then I think you're all set then :)

**Comment by xuanxu** [comment]
Yes, I also think having a single workflow is easier to maintain.

**Comment by mpadge** [comment]
This has all been addressed now via ropensci-org/buffy#23 and commits linked to in that issue.
