### ISSUE TITLE
Revert to including srr reports as part of review checks

### ISSUE THREAD

**Issue by noamross** [ropensci-review-tools/roreviewapi#62]
We previously included reports of `srr` standards compliance directly in the automated reports (e.g., https://github.com/ropensci/software-review/issues/603#issuecomment-1689418954).  These were quite helpful because it gave a way for statistical reviewers to get a sense of the compliance approach before they had to download anything to run on their own machine.  Can we return to this?

**Comment by mpadge** [comment]
So it seems that this ability has always existed, and still does. I just don't know what happened with https://github.com/ropensci/software-review/issues/615#issuecomment-1772393481. The report was generated, and [can be seen here](https://ropensci-review-tools.github.io/roreviewapi/static/galamm_srr26cfad15.html), but for some reason at that time the line linking to that did not appear in the checks report.

Anyway, if checks are re-run now, they definitely include link to the report, so this can be closed. Thanks!
