### ISSUE TITLE
Add "CI" envvar

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/roreviewapi#63]
So that `testthat::skip_on_ci()` can be used (ping @adamhsparks). General question was issued on rOpenSci semi-private slack:

> A request for input into design of rOpenSci's package checking service. Many CI systems implement common practices, notably through setting common environment variables to indicate jobs are running in a CI environment. Foremost among these is "CI", which is set on GitHub, GitLab, CircleCI, and likely lots of others, and used by testthat::skip_on_ci(). Our rOpenSci system does not use that. Instead, it places the onus on developers to implement appropriate environment variables and controls within their own tests and code. This is clearly more truly portable and robust, although it (potentially) burdens developers. Question is the extent to which we should ease that burden by presuming common workflows and tools. Note that use of testthat is not required, and other frameworks are acceptable, including for test control. Adding environment variables like these is as assumption, one which may be subject to change in the future, and which may have unforeseen consequences? What are people's thoughts on convenience added by us complying with these kinds of (currently) common practices, versus loss of clarity, portability, robustness, and the like? ... Or an alternative option of us adding our own distinct variable, and documenting how folk can use that?

Responses were supportive of aligning our system with general patterns through adding this variable. Conveniently, `skip_on_ci()` only tests for presence of an envvar with that name, regardless of its value. That would enable us to use `CI = "ropensci"`, so tests could be fine-tuned for our system only. Thanks to input from @assignUser, @pachadotdev @infotroph

**Comment by adamhsparks** [comment]
Thank you! Debugging CI is so frustrating, this definitely makes submitting some tricky packages easier.

**Comment by mpadge** [comment]
@adamhsparks Done now; service is scheduled to re-deploy 12 hours from now, after which time `"CI" = "ropensci"` will be included, so `skip_on_ci()` will work.
