### ISSUE TITLE
r_bg process keeps hanging

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/roreviewapi#7]
@gaborcsardi This repo powers rOpenSci's new bot service to provide automated reviews of packages. The bot calls a `callr::r_bg` process and responds immediately afterward with generic content. The `r_bg` process then does the work of installing all required system libraries and running` goodpractice` and other checks. The whole thing works locally, but when deployed as `docker-compose` service frequently keeps hanging before it completes. There's an inbuilt logger which dumps `stdout` (and `stderr`) logs from the `r_bg` process for inspection, and that shows that the process indeed just hangs, for example during simple system installs. Calling a second time often clears things and everything works.

In addition to sending `stdout` & `stderr` to logs, i've set `poll_connection = FALSE` and `supervise = TRUE`. Any suggestions would be greatly appreciated! Thanks!

**Comment by gaborcsardi** [comment]
> There's an inbuilt logger which dumps stdout (and stderr) logs from the r_bg process for inspection

I don't know what this means. Another process? What are the `stdout` and `stderr` arguments of `callr::r_bg()`? 

> In addition to sending stdout & stderr to logs,

Again, what does this mean? If they are sent to files, then what is the inbuilt logger doing?

>  i've set poll_connection = FALSE and supervise = TRUE

I would not do this, if anything they may cause more problems.

My guess is that this is because you don't read out the standard output and/or error, but I would need to see some actual code to be sure.

**Comment by mpadge** [comment]
Thanks @gaborcsardi. The code is just this:
https://github.com/ropensci-review-tools/roreviewapi/blob/85aa7f8415739b05806b38c0b1c7478135d47a3c/R/plumber.R#L22-L29

The main process, `editor_check()`, is primarily `remotes::system_requirements` -> `install_deps` then `goodpractice` plus a few more bells and whistles. The `stderr`/`stdout` list items are names of non-temp files in `~/.cache/...`. I opted for that over reading directly from the inbuilt logs because (1) this is all called via a plumber API, so process handle is inaccessible anyway; and (2) so that the logs would be retained and could be inspected at later times (with identical calls purging previous logs).

I've always called it with `supervise = TRUE`, because we want to make sure these background processes are appropriately killed. The `poll_connection = FALSE` was just an attempt to see whether that was somehow interfering, but makes no difference in terms of this issue.

**Comment by gaborcsardi** [comment]
> The code is just this:

IDK how plumber works, but it seems like `ps` is not stored anywhere, so when the function exits, there won't be any references to it, and processx will kill it at the next garbage collection. E.g.

```r
p <- processx::process$new("sleep", "100000")
ps::ps_children()
#> [[1]]
#> <ps::ps_handle> PID=79642, NAME=sleep, AT=2021-07-22 19:40:50

rm(p)
gc()
#>          used (Mb) gc trigger (Mb) limit (Mb) max used (Mb)
#> Ncells 454376 24.3     926977 49.6         NA   677337 36.2
#> Vcells 908386  7.0    8388608 64.0      16384  1871065 14.3

ps::ps_children()
#> list()
```

**Comment by mpadge** [comment]
Yeah, it does seem to be something like that. The main plumber process should remain active the whole time, but `ps` is bound to the environment of one particular function that exits straight away, so it can still be `gc`-ed I suppose. I'll find out what the parent process of a plumber call is and see if I can bind `ps` there to stop it being removed. Thanks!

**Comment by mpadge** [comment]
Yep, that solved it - thank you Gabor!!
